### PR TITLE
Cleaned up some code

### PR DESCRIPTION
**Pull request by ghost**
This pull is mostly to make sure this project is still alive. If
I get a responce, I will begin working on the TODOs.

### CODE REVIEW

**Comment by ghost** [comment]
Turning into a web app would be pretty cool. I haven't used Tornado or CherryPy before, so I won't be much help there.

I'm also sharpening my python skills. I am currently going through the programs listed here: http://liquidthink.net/uploads/2014/12/a6fN92L1.jpg one by one. So far it has been good practice because the tasks are varied and allows me to explore the basics of some python tools.

**Comment by brando56894** [comment]
Cool so it looks like we're probably around the same skill level. I re-learned most of it off of CodeAcademy. 

If you can think of any cool features to add go right ahead because I'm pretty much out of ideas, hence the reason why I haven't been working on it much lately. The one thing that annoyed me in the original code and still annoys me in this is the lack of evenly distributed rolls. For example, sometimes you'll roll a two three times in a row then roll a different number then back to rolling two more threes. I researched this a bit and it's not a problem with the random number generator, because it is truly random, it's just not evenly distributed because it's not really meant to be that way. It either makes the game too easy (by giving you too much gold/health potions/weapons) or it makes it too difficult (too many monster attacks before you even have a good weapon or enough money/potions).

I also implemented a save and load feature using pickle, but IIRC the loading doesn't work correctly for some reason. It's kind of pointless now because there's no reason to save the game since it can be finished in about 15 minutes. I was thinking about adding in an experience system where you would gain levels and get better equipment, as well as make the monsters more difficult, but I'm not really sure on how to do the leveling system since I suck at math hahaha I'm assuming it would have to be something like **new_level = current_level + n** where **n** is an exponential counter or something. I already have the XP points laid out and added to the fighting sequence so your character accrues XP but it currently doesn't do anything. If you wanna take a stab at that go for it. Thing is, the game will still be finished in about 15-20 minutes and will seem repetitive and boring after maybe two plays.

Does python have any GUI libraries? Converting it into a GUI game (point and click) would definitely help, I did that originally in college when I learned Java and used the Swing library and it made it look at lot nicer.

**Comment by ghost** [comment]
I will take a look at the roll functionality. Me and my friends started making a gui-based text adventure using kivy, but we split up and the game was never finished. Fortunately the 3000+ lines of code is still up: 
https://github.com/Autzmosis/dungeonGame

I coded the entire thing and after we split up, I pushed the remnants to the group repository using my old account. I know my way around kivy (It is really intuitive to learn) so I can definitely convert this into a gui game. With kivy you can convert the game into a desktop application or mobile application. I don't think kivy can help make it into a web app, though. If you look at the charANPC.py the leveling system I was using was more so per stat (giving the user choice) instead of per level. I'm pretty sure I used a cubic function to determine leveling up and exp needed.

If you add in character classes, special moves and items, the game will last a lot longer and would encourage multiple plays

**Comment by ghost** [comment]
Suggestion: Instead of rolls, you could use a zork-style of gameplay (you could create a virtual map that the player would traverse (choosing between going north, south, etc) to get to a certain point in the dungoen).

**Comment by brando56894** [comment]
Awesome! Both sound like great ideas. I'll have to look into Kivy, sounds interesting. Something like Zork would definitely spice it up a bit. I do most of my coding in testing, I was pushing stuff last night that I hadn't committed yet but my friend came over and side-tracked me haha I'll merge it into master tomorrow if I remember.

**Comment by ghost** [comment]
I have been coding in featurebuffs. So far I have created some superRandom functions, that should make things more random, and have begun optimizing code in main.py

By the time you merge testing into master, featurebuffs should also be ready to merge.

**Pull request merged**
